language: objective-c
osx_image: xcode11.6
script:
- xcodebuild test -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,name=iPhone XS Max" -sdk iphonesimulator12.1 CODE_SIGNING_REQUIRED=NO
